"""
Treatment Projection Analysis - Late Fusion Model (Clinico-ResNet + Molecular)
Author: Fadel Batal
Revised: June 2026

CONFIDENCE INTERVAL METHODOLOGY
---------------------------------
Point estimates (risk score and 1/3/5-yr PFS) come from an unregularized Cox
proportional hazards model refit on the full discovery cohort using the original
scalers ("refit_fusion_model"). This removes LASSO shrinkage bias while keeping
all quantities on the same scale.

Survival curves and their 95% confidence bands are derived entirely from the
same model family: the center line is refit_fusion_model's predicted survival
function; the band is the 2.5th-97.5th percentile of 1,000 bootstrap survival
curves. Each bootstrap entry pairs an unregularized Cox model with its own
StandardScaler refit on that bootstrap resample, ensuring the scaling and
fitting steps are consistent within every iteration. At inference time each
bootstrap entry applies its own scaler to the raw risk scores before predicting,
so the CI reflects both coefficient uncertainty and scaling variability.
Percentile-based intervals are used rather than ±1.96×std to respect the [0,1]
bounds of survival probabilities and avoid symmetry assumptions that do not hold
near 0 or 1. Because point estimates and CIs are derived from the same model
family on the same scale, the point estimate is guaranteed to fall within its
own confidence band.
"""

import warnings
warnings.filterwarnings('ignore')

import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import time
from sksurv.linear_model import CoxPHSurvivalAnalysis
from sksurv.metrics import concordance_index_censored
from sklearn.preprocessing import StandardScaler

# =============================================================================
# CONFIGURATION
# =============================================================================

# Repo root: one level up from this script's folder (04_Analysis/)
REPO_ROOT   = Path(__file__).resolve().parent.parent
DLM1_DIR    = REPO_ROOT / '01_DLM1_Clinico_ResNet'
MOL_DIR     = REPO_ROOT / '02_Molecular_Subtype'
DLM2_DIR    = REPO_ROOT / '03_Late_Fusion_DLM2'

# Base model artifacts
CR_ESTIMATOR  = DLM1_DIR / 'outputs' / 'models' / 'estimator.pkl'
MOL_ESTIMATOR = MOL_DIR  / 'outputs' / 'models' / 'estimator.pkl'

# Patient-level data files (not included in repo — produced by the training notebooks
# after downloading CBTN data; see README.md for data access instructions)
X_CLINICAL_PATH  = DLM1_DIR / 'outputs' / 'models' / 'X_clinical.pkl'
X_RESNET_PATH    = DLM1_DIR / 'outputs' / 'models' / 'X_resnet.pkl'
X_MOLECULAR_PATH = MOL_DIR  / 'outputs' / 'models' / 'X_molecular.pkl'
Y_PATH           = MOL_DIR  / 'outputs' / 'models' / 'y.pkl'

# DL-M2 fusion model outputs (produced by 03_Late_Fusion_DLM2/Late_Fusion_Modeling_ResNet.py)
# Update FUSION_DIR to the timestamped output folder generated by that script.
FUSION_DIR            = DLM2_DIR / 'outputs' / 'pairwise_resnet_molecular_YYYYMMDD_HHMMSS'
FUSION_MODEL          = FUSION_DIR / 'model.pkl'
FUSION_SCALERS        = FUSION_DIR / 'scalers.pkl'
FUSION_THRESHOLD_FILE = FUSION_DIR / 'threshold.txt'

OUTPUT_BASE       = REPO_ROOT / '04_Analysis' / 'outputs' / 'treatment_scenario_DLM2'
SCENARIOS_DIR     = OUTPUT_BASE / 'scenarios'
BOOTSTRAP_DIR     = OUTPUT_BASE / 'bootstrap_uncertainty'
VISUALIZATION_DIR = OUTPUT_BASE / 'visualizations'

for dir_path in [SCENARIOS_DIR, BOOTSTRAP_DIR, VISUALIZATION_DIR]:
    dir_path.mkdir(parents=True, exist_ok=True)

N_BOOTSTRAP = 1000
RANDOM_SEED = 42
SAVE_MODELS = True

# Survival time points in months (1, 3, 5 years)
SURV_TIME_POINTS = [12, 36, 60]
SURV_LABELS      = ['1yr', '3yr', '5yr']

# Treatment scenarios — defined once, shared across all functions
TREATMENT_SCENARIOS = [
    {'label': 'Biopsy only + Chemo: Yes',               'resection': 1/3, 'chemo': 1, 'color': '#377eb8', 'linestyle': '-'},
    {'label': 'Partial resection + Chemo: No',          'resection': 2/3, 'chemo': 0, 'color': '#4daf4a', 'linestyle': '--'},
    {'label': 'Partial resection + Chemo: Yes',         'resection': 2/3, 'chemo': 1, 'color': '#984ea3', 'linestyle': '--'},
    {'label': 'Gross/Near total resection + Chemo: No', 'resection': 3/3, 'chemo': 0, 'color': '#ff7f00', 'linestyle': '-.'},
]

sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 150
plt.rcParams['savefig.dpi'] = 300


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def create_structured_outcomes(df):
    return np.array(
        [(bool(e), float(t)) for e, t in zip(df['Event'], df['Progression Free Survival'])],
        dtype=[("Event", bool), ("Progression Free Survival", float)]
    )


def parse_fusion_threshold(filepath):
    try:
        with open(filepath, 'r') as f:
            for line in f:
                if 'Fusion threshold' in line and ':' in line:
                    return float(line.split(':')[1].strip())
    except Exception as e:
        print(f"  Could not parse threshold: {e}")
    return None


def _fusion_survival_curve(model, cr_risk_scaled, mol_risk_scaled, time_points):
    """Predict survival curve from a fitted fusion model given pre-scaled inputs."""
    fusion_input = np.array([[cr_risk_scaled, mol_risk_scaled]])
    surv_fn = model.predict_survival_function(fusion_input)[0]
    if hasattr(surv_fn, 'x') and len(surv_fn.x) > 0:
        t_min, t_max = surv_fn.x[0], surv_fn.x[-1]
    else:
        t_min, t_max = 0, 200
    return np.array([surv_fn(np.clip(t, t_min, t_max)) for t in time_points])


def get_fusion_survival_curves_with_uncertainty(cr_risk_raw, mol_risk_raw,
                                                refit_fusion_model,
                                                original_scaler_CR,
                                                original_scaler_mol,
                                                bootstrap_entries,
                                                time_points):
    """
    Point estimate from refit_fusion_model using original scalers.
    95% CI from 2.5th-97.5th percentiles of bootstrap survival curves,
    where each bootstrap entry applies its own scaler before predicting.
    Both use raw risk scores as input so scaling is handled internally,
    ensuring consistency within each model.
    """
    # Point estimate — original scalers + refit model
    cr_scaled_point  = original_scaler_CR.transform([[cr_risk_raw]])[0][0]
    mol_scaled_point = original_scaler_mol.transform([[mol_risk_raw]])[0][0]
    point_curve = _fusion_survival_curve(
        refit_fusion_model, cr_scaled_point, mol_scaled_point, time_points)

    # Bootstrap curves — each entry uses its own scaler for consistency
    boot_curves = []
    for entry in bootstrap_entries:
        cr_sc  = entry['scaler_cr'].transform([[cr_risk_raw]])[0][0]
        mol_sc = entry['scaler_mol'].transform([[mol_risk_raw]])[0][0]
        boot_curves.append(
            _fusion_survival_curve(entry['model'], cr_sc, mol_sc, time_points))
    boot_curves = np.array(boot_curves)

    return {
        'point':    point_curve,
        'ci_lower': np.percentile(boot_curves, 2.5,  axis=0),
        'ci_upper': np.percentile(boot_curves, 97.5, axis=0),
    }


def generate_fusion_treatment_scenarios(patient_id, X_CR, X_mol,
                                        base_CR_model, base_mol_model,
                                        refit_fusion_model,
                                        original_scaler_CR, original_scaler_mol,
                                        fusion_threshold):
    """Risk score + risk group per scenario using the refit fusion estimator."""
    cr_features  = X_CR.loc[patient_id].copy()
    mol_features = X_mol.loc[patient_id].copy()

    mol_risk_raw    = base_mol_model.predict([mol_features.values])[0]
    mol_risk_scaled = original_scaler_mol.transform([[mol_risk_raw]])[0][0]

    results = []
    for scenario in TREATMENT_SCENARIOS:
        sf = cr_features.copy()
        sf['Extent of Tumor Resection'] = scenario['resection']
        sf['Chemotherapy']              = scenario['chemo']

        cr_risk_raw    = base_CR_model.predict([sf.values])[0]
        cr_risk_scaled = original_scaler_CR.transform([[cr_risk_raw]])[0][0]

        fusion_input = np.array([[cr_risk_scaled, mol_risk_scaled]])
        fusion_risk  = float(refit_fusion_model.predict(fusion_input)[0])
        risk_group   = 'High' if fusion_risk > fusion_threshold else 'Low'

        results.append({
            'Patient_ID':      patient_id,
            'Treatment_Label': scenario['label'],
            'Resection':       scenario['label'].split(' + ')[0],
            'Chemotherapy':    'Yes' if scenario['chemo'] == 1 else 'No',
            'CR_Risk_Raw':     base_CR_model.predict([sf.values])[0],
            'Mol_Risk_Raw':    mol_risk_raw,
            'Fusion_Risk':     fusion_risk,
            'Risk_Group':      risk_group,
        })

    return pd.DataFrame(results)


def plot_fusion_patient_survival_scenarios(patient_id, X_CR, X_mol,
                                           base_CR_model, base_mol_model,
                                           refit_fusion_model,
                                           bootstrap_entries,
                                           original_scaler_CR, original_scaler_mol,
                                           fusion_threshold, save_path,
                                           actual_pfs=None, actual_event=None):
    cr_features  = X_CR.loc[patient_id].copy()
    mol_features = X_mol.loc[patient_id].copy()

    # Use refit model to determine time axis
    cr_risk_raw_base    = base_CR_model.predict([cr_features.values])[0]
    mol_risk_raw_base   = base_mol_model.predict([mol_features.values])[0]
    cr_scaled_base      = original_scaler_CR.transform([[cr_risk_raw_base]])[0][0]
    mol_scaled_base     = original_scaler_mol.transform([[mol_risk_raw_base]])[0][0]

    test_surv_fn = refit_fusion_model.predict_survival_function(
        np.array([[cr_scaled_base, mol_scaled_base]]))[0]
    if hasattr(test_surv_fn, 'x') and len(test_surv_fn.x) > 0:
        min_time, max_time = test_surv_fn.x[0], test_surv_fn.x[-1]
    else:
        min_time, max_time = 0, 150

    time_points = np.linspace(min_time, max_time, 100)

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    ax1 = axes[0]
    scenario_data = []

    # Molecular risk is fixed across scenarios (only CR features vary with treatment)
    mol_risk_raw = base_mol_model.predict([mol_features.values])[0]

    for scenario in TREATMENT_SCENARIOS:
        sf = cr_features.copy()
        sf['Extent of Tumor Resection'] = scenario['resection']
        sf['Chemotherapy']              = scenario['chemo']

        cr_risk_raw = base_CR_model.predict([sf.values])[0]

        # Survival curves: point from refit model, CI from bootstrap percentiles.
        # Each bootstrap entry scales with its own scaler — fully consistent.
        surv_stats = get_fusion_survival_curves_with_uncertainty(
            cr_risk_raw, mol_risk_raw,
            refit_fusion_model,
            original_scaler_CR, original_scaler_mol,
            bootstrap_entries, time_points)

        # Risk score: point from refit model; CI from bootstrap percentiles.
        # Same model family and scale — point estimate always within its CI.
        cr_risk_scaled  = original_scaler_CR.transform([[cr_risk_raw]])[0][0]
        mol_risk_scaled = original_scaler_mol.transform([[mol_risk_raw]])[0][0]
        fusion_input    = np.array([[cr_risk_scaled, mol_risk_scaled]])
        fusion_risk     = float(refit_fusion_model.predict(fusion_input)[0])

        boot_fusion_risks = np.array([
            entry['model'].predict(
                np.array([[
                    entry['scaler_cr'].transform([[cr_risk_raw]])[0][0],
                    entry['scaler_mol'].transform([[mol_risk_raw]])[0][0],
                ]])
            )[0]
            for entry in bootstrap_entries
        ])
        fusion_risk_ci_lower = float(np.percentile(boot_fusion_risks, 2.5))
        fusion_risk_ci_upper = float(np.percentile(boot_fusion_risks, 97.5))
        risk_group = 'High' if fusion_risk > fusion_threshold else 'Low'

        ax1.plot(time_points, surv_stats['point'],
                 color=scenario['color'], linestyle=scenario['linestyle'],
                 linewidth=2.5, label=scenario['label'], alpha=0.9)
        ax1.fill_between(time_points, surv_stats['ci_lower'], surv_stats['ci_upper'],
                         color=scenario['color'], alpha=0.15)

        # Survival at 1, 3, 5 years with 95% CI
        row = {
            'scenario':             scenario['label'],
            'fusion_risk':          fusion_risk,
            'fusion_risk_ci_lower': fusion_risk_ci_lower,
            'fusion_risk_ci_upper': fusion_risk_ci_upper,
            'risk_group':           risk_group,
        }
        for t_months, t_label in zip(SURV_TIME_POINTS, SURV_LABELS):
            if max_time >= t_months:
                idx = np.argmin(np.abs(time_points - t_months))
                row[t_label]               = surv_stats['point'][idx]
                row[f'{t_label}_ci_lower'] = surv_stats['ci_lower'][idx]
                row[f'{t_label}_ci_upper'] = surv_stats['ci_upper'][idx]
            else:
                row[t_label]               = None
                row[f'{t_label}_ci_lower'] = None
                row[f'{t_label}_ci_upper'] = None
        scenario_data.append(row)

    if actual_pfs is not None and actual_event is not None and actual_pfs <= max_time:
        if actual_event:
            ax1.axvline(actual_pfs, color='black', linestyle=':', linewidth=2.5,
                        label=f'Actual Progression ({actual_pfs:.1f} mo)', zorder=1, alpha=0.7)
        else:
            ax1.axvline(actual_pfs, color='gray', linestyle=':', linewidth=2.5,
                        label=f'Censored at {actual_pfs:.1f} mo', zorder=1, alpha=0.7)

    ax1.set_xlabel('Time (months)', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Progression-Free Survival Probability', fontsize=12, fontweight='bold')
    ax1.set_title(f'Patient {patient_id}: Fusion Model (ResNet + Molecular)\nSurvival Curves Under Treatment Scenarios',
                  fontsize=14, fontweight='bold')
    ax1.legend(loc='lower left', fontsize=9, framealpha=0.95)
    ax1.grid(alpha=0.3)
    ax1.set_ylim(0, 1.05)
    ax1.set_xlim(0, max_time)

    # Table
    ax2 = axes[1]
    ax2.axis('off')

    scenario_df = pd.DataFrame(scenario_data)
    headers = ['Treatment Scenario', 'Fusion Risk\n(95% CI)', 'Risk\nGroup']
    for t_label in SURV_LABELS:
        if scenario_df[t_label].notna().any():
            headers.append(t_label.replace('yr', '-yr PFS\n(95% CI)'))

    table_data = []
    for _, row in scenario_df.iterrows():
        rd = [
            row['scenario'],
            f"{row['fusion_risk']:.2f}\n[{row['fusion_risk_ci_lower']:.2f}, {row['fusion_risk_ci_upper']:.2f}]",
            row['risk_group'],
        ]
        for t_label in SURV_LABELS:
            if row[t_label] is not None:
                rd.append(
                    f"{row[t_label]:.2f}\n"
                    f"[{row[f'{t_label}_ci_lower']:.2f}, {row[f'{t_label}_ci_upper']:.2f}]"
                )
            else:
                rd.append("N/A")
        table_data.append(rd)

    table = ax2.table(cellText=table_data, colLabels=headers,
                      cellLoc='center', loc='center',
                      colWidths=[0.35, 0.15, 0.15] + [0.12] * (len(headers) - 3))
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1, 3.2)

    for j in range(len(headers)):
        table[(0, j)].set_facecolor('#1a9850')
        table[(0, j)].set_text_props(weight='bold', color='white')

    for i in range(1, len(table_data) + 1):
        if i % 2 == 0:
            for j in range(len(headers)):
                table[(i, j)].set_facecolor('#f0f0f0')
        table[(i, 2)].set_facecolor('#ffcccc' if table_data[i-1][2] == 'High' else '#ccffcc')

    ax2.set_title(
        'Treatment Scenario Summary\n'
        'Point estimate from full-discovery refit; 95% CI = 2.5th–97.5th bootstrap percentile',
        fontsize=9, fontweight='bold', pad=20)

    if actual_pfs is not None and actual_event is not None:
        status = "Progressed" if actual_event else "Censored"
        fig.suptitle(f'Fusion Model Analysis for Patient {patient_id}\n'
                     f'Actual outcome: {status} at {actual_pfs:.1f} months',
                     fontsize=14, fontweight='bold', y=0.98)
    else:
        fig.suptitle(f'Fusion Model Analysis for Patient {patient_id}',
                     fontsize=14, fontweight='bold', y=0.98)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    plt.close()

    return scenario_df


# =============================================================================
# MAIN ANALYSIS PIPELINE
# =============================================================================

print("=" * 80)
print("TREATMENT PROJECTION ANALYSIS - LATE FUSION MODEL")
print("Clinico-ResNet + Molecular")
print("=" * 80)

# =============================================================================
# STEP 1: LOAD DATA AND MODELS
# =============================================================================

print("\nStep 1: Loading data and models...")

X_clinical  = pd.read_pickle(X_CLINICAL_PATH)
X_resnet    = pd.read_pickle(X_RESNET_PATH)
X_molecular = pd.read_pickle(X_MOLECULAR_PATH)
y           = pd.read_pickle(Y_PATH)

X_clinical_features  = X_clinical.drop(columns='Cohort')
X_resnet_features    = X_resnet.drop(columns='Cohort', errors='ignore')
X_CR                 = X_clinical_features.merge(X_resnet_features, left_index=True, right_index=True)
X_molecular_features = X_molecular.drop(columns='Cohort', errors='ignore')

X_CR_full  = X_CR.merge(y, left_index=True, right_index=True)
X_mol_full = X_molecular_features.merge(y, left_index=True, right_index=True)

# Base component models — used only to produce raw risk scores
with open(CR_ESTIMATOR, 'rb') as f:
    base_CR_model = pickle.load(f)
with open(MOL_ESTIMATOR, 'rb') as f:
    base_mol_model = pickle.load(f)

# Original fusion model and scalers — scalers used throughout for
# point estimates; original fusion model retained only for threshold parsing
with open(FUSION_MODEL, 'rb') as f:
    original_fusion_model = pickle.load(f)
with open(FUSION_SCALERS, 'rb') as f:
    all_scalers = pickle.load(f)

original_scaler_CR  = all_scalers['Clinical-ResNet']
original_scaler_mol = all_scalers['Molecular']

fusion_threshold = parse_fusion_threshold(FUSION_THRESHOLD_FILE)
if fusion_threshold is None:
    print("  Threshold not found — will recompute on refit scale after fitting refit model")
else:
    print(f"  Fusion threshold (from file): {fusion_threshold:.6f}")

# =============================================================================
# STEP 2: PATIENT INTERSECTIONS
# =============================================================================

print("\nStep 2: Finding patient intersections...")

CR_discovery_ids  = set(X_CR_full[X_CR_full['Cohort'] == 'Discovery'].index)
CR_replicate_ids  = set(X_CR_full[X_CR_full['Cohort'] == 'Replicate'].index)
mol_discovery_ids = set(X_mol_full[X_mol_full['Cohort'] == 'Discovery'].index)
mol_replicate_ids = set(X_mol_full[X_mol_full['Cohort'] == 'Replicate'].index)

discovery_intersection = sorted(CR_discovery_ids & mol_discovery_ids)
replicate_intersection  = sorted(CR_replicate_ids  & mol_replicate_ids)

print(f"  Discovery intersection: {len(discovery_intersection)} patients")
print(f"  Replicate intersection: {len(replicate_intersection)} patients")

drop_cols = ['Progression Free Survival', 'Event', 'Cohort']
X_CR_discovery  = X_CR_full.loc[discovery_intersection].drop(columns=drop_cols)
X_CR_replicate  = X_CR_full.loc[replicate_intersection].drop(columns=drop_cols)
X_mol_discovery = X_mol_full.loc[discovery_intersection].drop(columns=drop_cols)
X_mol_replicate = X_mol_full.loc[replicate_intersection].drop(columns=drop_cols)

y_discovery_full = y.loc[discovery_intersection, ['Progression Free Survival', 'Event']]
y_replicate_full = y.loc[replicate_intersection,  ['Progression Free Survival', 'Event']]
y_discovery      = create_structured_outcomes(y_discovery_full)
y_replicate      = create_structured_outcomes(y_replicate_full)

# Pre-compute raw risk scores for all patients (base models are fixed)
cr_disc_risks_raw  = base_CR_model.predict(X_CR_discovery.values)
mol_disc_risks_raw = base_mol_model.predict(X_mol_discovery.values)
cr_rep_risks_raw   = base_CR_model.predict(X_CR_replicate.values)
mol_rep_risks_raw  = base_mol_model.predict(X_mol_replicate.values)

# =============================================================================
# STEP 3: REFIT FUSION MODEL ON FULL DISCOVERY SET
# =============================================================================
# This is the deployment estimator for all point estimates. It uses the
# original scalers (same as training) and alpha=0 to remove LASSO shrinkage
# bias. The threshold is recomputed on this scale so everything is consistent.

print("\nStep 3: Fitting refit fusion model on full discovery set...")

cr_disc_scaled  = original_scaler_CR.transform(cr_disc_risks_raw.reshape(-1, 1)).flatten()
mol_disc_scaled = original_scaler_mol.transform(mol_disc_risks_raw.reshape(-1, 1)).flatten()
X_fusion_disc   = np.column_stack([cr_disc_scaled, mol_disc_scaled])

refit_fusion_model = CoxPHSurvivalAnalysis(alpha=0.0, verbose=0)
refit_fusion_model.fit(X_fusion_disc, y_discovery)
print(f"  Refit fusion CoxPH fitted on {len(discovery_intersection)} discovery patients")

# Recompute threshold on refit scale (median discovery risk)
refit_disc_scores = refit_fusion_model.predict(X_fusion_disc)
fusion_threshold  = float(np.median(refit_disc_scores))
print(f"  Risk threshold (refit-scale median discovery risk): {fusion_threshold:.6f}")

cr_rep_scaled   = original_scaler_CR.transform(cr_rep_risks_raw.reshape(-1, 1)).flatten()
mol_rep_scaled  = original_scaler_mol.transform(mol_rep_risks_raw.reshape(-1, 1)).flatten()
X_fusion_rep    = np.column_stack([cr_rep_scaled, mol_rep_scaled])
refit_pred_rep  = refit_fusion_model.predict(X_fusion_rep)

harrell_disc = concordance_index_censored(
    y_discovery['Event'], y_discovery['Progression Free Survival'], refit_disc_scores)[0]
harrell_rep  = concordance_index_censored(
    y_replicate['Event'], y_replicate['Progression Free Survival'], refit_pred_rep)[0]
print(f"  Refit fusion CoxPH — Harrell C: Discovery={harrell_disc:.4f}  Replicate={harrell_rep:.4f}")

# =============================================================================
# STEP 4: BOOTSTRAP UNCERTAINTY QUANTIFICATION
# =============================================================================
# Each bootstrap entry stores its own scaler pair alongside the fitted model.
# This ensures that at inference time each entry scales the raw risk scores
# with the same distribution it was trained on — fully consistent.

print("\nStep 4: Bootstrap uncertainty quantification...")
print("  Each bootstrap entry stores model + scaler pair for consistent inference.")

np.random.seed(RANDOM_SEED)
bootstrap_entries  = []   # list of {'model', 'scaler_cr', 'scaler_mol'}
bootstrap_metadata = []
start_time = time.time()

for i in range(N_BOOTSTRAP):
    iter_start = time.time()
    print(f"  [{i+1}/{N_BOOTSTRAP}] Bootstrap iteration {i+1}...", end='', flush=True)

    try:
        indices = np.random.choice(len(discovery_intersection), len(discovery_intersection), replace=True)

        cr_boot_raw  = cr_disc_risks_raw[indices]
        mol_boot_raw = mol_disc_risks_raw[indices]

        # Refit scaler on this bootstrap sample
        scaler_cr_b  = StandardScaler().fit(cr_boot_raw.reshape(-1, 1))
        scaler_mol_b = StandardScaler().fit(mol_boot_raw.reshape(-1, 1))

        cr_boot_scaled  = scaler_cr_b.transform(cr_boot_raw.reshape(-1, 1)).flatten()
        mol_boot_scaled = scaler_mol_b.transform(mol_boot_raw.reshape(-1, 1)).flatten()
        X_fusion_boot   = np.column_stack([cr_boot_scaled, mol_boot_scaled])

        y_boot = y_discovery[indices]

        boot_model = CoxPHSurvivalAnalysis(alpha=0.0, verbose=0)
        boot_model.fit(X_fusion_boot, y_boot)

        # Store model AND scalers together — inseparable for correct inference
        bootstrap_entries.append({
            'model':      boot_model,
            'scaler_cr':  scaler_cr_b,
            'scaler_mol': scaler_mol_b,
        })

        bootstrap_metadata.append({
            'iteration':        i + 1,
            'n_samples':        len(indices),
            'n_unique_samples': len(np.unique(indices)),
            'CR_weight':        boot_model.coef_[0],
            'Mol_weight':       boot_model.coef_[1],
            'cr_scaler_mean':   scaler_cr_b.mean_[0],
            'cr_scaler_std':    scaler_cr_b.scale_[0],
            'mol_scaler_mean':  scaler_mol_b.mean_[0],
            'mol_scaler_std':   scaler_mol_b.scale_[0],
            'converged':        True,
        })

        iter_time = time.time() - iter_start
        print(f" OK ({iter_time:.1f}s, CR={boot_model.coef_[0]:.3f}, Mol={boot_model.coef_[1]:.3f})", flush=True)

        if (i + 1) % 10 == 0 or (i + 1) == N_BOOTSTRAP:
            pd.DataFrame(bootstrap_metadata).to_csv(BOOTSTRAP_DIR / 'bootstrap_metadata.csv', index=False)

    except Exception as e:
        print(f" ERROR: {str(e)}", flush=True)
        bootstrap_metadata.append({'iteration': i + 1, 'converged': False, 'error': str(e)})

elapsed = time.time() - start_time
print(f"\n  Bootstrap completed in {elapsed/60:.1f} minutes")
print(f"  Successful iterations: {len(bootstrap_entries)}/{N_BOOTSTRAP}")

pd.DataFrame(bootstrap_metadata).to_csv(BOOTSTRAP_DIR / 'bootstrap_metadata.csv', index=False)

if SAVE_MODELS:
    with open(BOOTSTRAP_DIR / 'bootstrap_entries.pkl', 'wb') as f:
        pickle.dump(bootstrap_entries, f)
    print(f"  Saved bootstrap entries (model + scaler pairs)")

# Per-patient risk score CIs on replicate set
print(f"\n  Generating per-patient risk-score CIs for replicate cohort...")
replicate_boot_risks = []
for entry in bootstrap_entries:
    cr_sc  = entry['scaler_cr'].transform(cr_rep_risks_raw.reshape(-1, 1)).flatten()
    mol_sc = entry['scaler_mol'].transform(mol_rep_risks_raw.reshape(-1, 1)).flatten()
    replicate_boot_risks.append(
        entry['model'].predict(np.column_stack([cr_sc, mol_sc])))
replicate_boot_risks = np.array(replicate_boot_risks)

replicate_stats = pd.DataFrame({
    'SubjectID':          replicate_intersection,
    'Point_Risk':         refit_fusion_model.predict(X_fusion_rep),
    'Bootstrap_Mean':     replicate_boot_risks.mean(axis=0),
    'Bootstrap_Std':      replicate_boot_risks.std(axis=0),
    'Bootstrap_CI_Lower': np.percentile(replicate_boot_risks, 2.5,  axis=0),
    'Bootstrap_CI_Upper': np.percentile(replicate_boot_risks, 97.5, axis=0),
})
replicate_stats['Uncertainty'] = replicate_stats['Bootstrap_CI_Upper'] - replicate_stats['Bootstrap_CI_Lower']
replicate_stats.to_csv(BOOTSTRAP_DIR / 'replicate_predictions_with_uncertainty.csv', index=False)
print(f"  Replicate mean CI width: {replicate_stats['Uncertainty'].mean():.6f}")

# =============================================================================
# STEP 5: GENERATE TREATMENT SCENARIOS
# =============================================================================

print("\nStep 5: Generating treatment scenarios on replicate cohort...")

all_scenarios        = []
verification_records = []
resection_map = {1/3: 'Biopsy only', 2/3: 'Partial resection', 3/3: 'Gross/Near total resection'}
chemo_map     = {0: 'No', 1: 'Yes'}

for i, patient_id in enumerate(replicate_intersection, 1):
    print(f"  [{i}/{len(replicate_intersection)}] {patient_id}", end='\r')

    try:
        scenarios = generate_fusion_treatment_scenarios(
            patient_id, X_CR_replicate, X_mol_replicate,
            base_CR_model, base_mol_model,
            refit_fusion_model,
            original_scaler_CR, original_scaler_mol,
            fusion_threshold
        )
        all_scenarios.append(scenarios)

        actual_resection = X_CR_replicate.loc[patient_id, 'Extent of Tumor Resection']
        actual_chemo     = X_CR_replicate.loc[patient_id, 'Chemotherapy']
        resection_label  = next((lbl for val, lbl in resection_map.items()
                                 if abs(actual_resection - val) < 0.01), None)

        if resection_label:
            matching_label    = f"{resection_label} + Chemo: {chemo_map[int(actual_chemo)]}"
            matching_scenario = scenarios[scenarios['Treatment_Label'] == matching_label]

            if len(matching_scenario) == 1:
                # Verification against refit model (same scale)
                cr_raw  = base_CR_model.predict([X_CR_replicate.loc[patient_id].values])[0]
                mol_raw = base_mol_model.predict([X_mol_replicate.loc[patient_id].values])[0]
                cr_sc   = original_scaler_CR.transform([[cr_raw]])[0][0]
                mol_sc  = original_scaler_mol.transform([[mol_raw]])[0][0]
                actual_fusion_risk = float(refit_fusion_model.predict(np.array([[cr_sc, mol_sc]]))[0])
                scenario_risk      = matching_scenario['Fusion_Risk'].values[0]
                diff = abs(actual_fusion_risk - scenario_risk)
                verification_records.append({
                    'Patient_ID':           patient_id,
                    'Actual_Fusion_Risk':   actual_fusion_risk,
                    'Scenario_Fusion_Risk': scenario_risk,
                    'Difference':           diff,
                    'Status':               'Match' if diff < 1e-6 else 'Mismatch',
                })
            else:
                verification_records.append({
                    'Patient_ID':           patient_id,
                    'Actual_Fusion_Risk':   np.nan,
                    'Scenario_Fusion_Risk': np.nan,
                    'Difference':           np.nan,
                    'Status':               'Scenario_Removed',
                })

    except Exception as e:
        print(f"  [{i}/{len(replicate_intersection)}] {patient_id} - ERROR: {str(e)}")

print(f"\n  Generated scenarios for {len(all_scenarios)} patients")
all_scenarios_df = pd.concat(all_scenarios, ignore_index=True)
all_scenarios_df.to_csv(SCENARIOS_DIR / 'all_treatment_scenarios.csv', index=False)

if verification_records:
    verification_df = pd.DataFrame(verification_records)
    verification_df.to_csv(SCENARIOS_DIR / 'verification_results.csv', index=False)
    n_match    = (verification_df['Status'] == 'Match').sum()
    n_mismatch = (verification_df['Status'] == 'Mismatch').sum()
    n_removed  = (verification_df['Status'] == 'Scenario_Removed').sum()
    print(f"  Verification: {n_match} matches, {n_mismatch} mismatches, {n_removed} scenario_removed")

# =============================================================================
# STEP 6: SURVIVAL CURVE VISUALIZATIONS
# =============================================================================

print("\nStep 6: Generating survival curves with bootstrap uncertainty...")

summary_data    = []
failed_patients = []
start_time      = time.time()

for i, patient_id in enumerate(replicate_intersection, 1):
    if i > 1:
        elapsed     = time.time() - start_time
        eta_seconds = (elapsed / (i - 1)) * (len(replicate_intersection) - i)
        eta_str     = f"ETA: {eta_seconds/60:.1f}min"
    else:
        eta_str = "calculating..."

    print(f"  [{i}/{len(replicate_intersection)}] {patient_id} ({eta_str})...", end='\r')

    try:
        actual_pfs   = y_replicate_full.loc[patient_id, 'Progression Free Survival']
        actual_event = y_replicate_full.loc[patient_id, 'Event']

        scenario_summary = plot_fusion_patient_survival_scenarios(
            patient_id, X_CR_replicate, X_mol_replicate,
            base_CR_model, base_mol_model,
            refit_fusion_model,
            bootstrap_entries,
            original_scaler_CR, original_scaler_mol,
            fusion_threshold,
            VISUALIZATION_DIR / f'{patient_id}_fusion_survival_curves.png',
            actual_pfs=actual_pfs, actual_event=actual_event
        )
        scenario_summary['Patient_ID'] = patient_id
        summary_data.append(scenario_summary)

    except Exception as e:
        print(f"\n  [{i}/{len(replicate_intersection)}] {patient_id} - ERROR: {str(e)}")
        failed_patients.append({'Patient_ID': patient_id, 'Error': str(e)})

total_time = time.time() - start_time
print(f"\n  Generated visualizations for {len(summary_data)} patients")
print(f"  Total time: {total_time/60:.1f} minutes")

if summary_data:
    pd.concat(summary_data, ignore_index=True).to_csv(
        VISUALIZATION_DIR / 'fusion_survival_scenario_summaries.csv', index=False)
if failed_patients:
    pd.DataFrame(failed_patients).to_csv(VISUALIZATION_DIR / 'failed_patients.csv', index=False)
    print(f"  Failed patients: {len(failed_patients)}")

# =============================================================================
# STEP 7: HTML INDEX
# =============================================================================

print("\nStep 7: Creating HTML index...")

progressed_patients = y_replicate_full[y_replicate_full['Event']].index.tolist()
censored_patients   = y_replicate_full[~y_replicate_full['Event']].index.tolist()

html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>Treatment Projection Analysis - Fusion Model (ResNet + Molecular)</title>
    <style>
        body {{font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5;}}
        h1 {{color: #333; border-bottom: 3px solid #1a9850; padding-bottom: 10px;}}
        .summary {{background: #e8f5e9; padding: 15px; border-radius: 8px; margin-bottom: 20px;}}
        .controls {{background: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);}}
        .filter-btn {{padding: 10px 20px; border: 2px solid #1a9850; background: white; color: #1a9850; border-radius: 5px; cursor: pointer; font-weight: bold; margin: 5px;}}
        .filter-btn:hover, .filter-btn.active {{background: #1a9850; color: white;}}
        .patient-card {{background: white; margin: 20px 0; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);}}
        .patient-header {{font-size: 18px; font-weight: bold; color: #1a9850; margin-bottom: 15px;}}
        img {{width: 100%; border: 1px solid #ddd; border-radius: 4px; cursor: pointer;}}
    </style>
    <script>
        function filterPatients(category) {{
            document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            event.target.classList.add('active');
            document.querySelectorAll('.patient-card').forEach(c => {{
                c.style.display = (category === 'all' || c.dataset.categories.split(',').includes(category))
                    ? 'block' : 'none';
            }});
        }}
    </script>
</head>
<body>
    <h1>Treatment Projection Analysis — Fusion Model (Clinico-ResNet + Molecular)</h1>
    <div class="summary">
        <strong>Analysis Complete:</strong> {len(summary_data)}/{len(replicate_intersection)} patients<br>
        <strong>Bootstrap Entries:</strong> {len(bootstrap_entries)}<br>
        <strong>Fusion Threshold (refit scale):</strong> {fusion_threshold:.6f}<br>
        <strong>Mean CI Width (Replicate):</strong> {replicate_stats['Uncertainty'].mean():.6f}<br>
        <strong>Processing Time:</strong> {total_time/60:.1f} minutes
    </div>
    <div class="controls">
        <strong>Filter Patients:</strong>
        <button class="filter-btn active" onclick="filterPatients('all')">All ({len(replicate_intersection)})</button>
        <button class="filter-btn" onclick="filterPatients('progressed')">Progressed ({len(progressed_patients)})</button>
        <button class="filter-btn" onclick="filterPatients('censored')">Censored ({len(censored_patients)})</button>
    </div>
"""

failed_ids = {p['Patient_ID'] for p in failed_patients}
for patient_id in replicate_intersection:
    if patient_id in failed_ids:
        continue
    outcome  = y_replicate_full.loc[patient_id]
    status   = "Progressed" if outcome['Event'] else "Censored"
    category = 'progressed' if outcome['Event'] else 'censored'
    html_content += f"""
    <div class="patient-card" data-categories="{category}">
        <div class="patient-header">Patient: {patient_id} ({status} at {outcome['Progression Free Survival']:.1f} months)</div>
        <img src="{patient_id}_fusion_survival_curves.png" alt="Survival Curves"
             onclick="window.open('{patient_id}_fusion_survival_curves.png', '_blank')">
    </div>"""

html_content += "\n</body></html>"

with open(VISUALIZATION_DIR / 'index.html', 'w') as f:
    f.write(html_content)
print(f"  Created: {VISUALIZATION_DIR}/index.html")

# =============================================================================
# SUMMARY
# =============================================================================

print("\n" + "=" * 80)
print("FUSION MODEL TREATMENT PROJECTION ANALYSIS COMPLETE")
print("Clinico-ResNet + Molecular")
print("=" * 80)
print(f"\n  Discovery patients: {len(discovery_intersection)}")
print(f"  Replicate patients: {len(replicate_intersection)}")
print(f"  Treatment scenarios: {len(all_scenarios_df)} total")
print(f"  Bootstrap entries:   {len(bootstrap_entries)}")
print(f"  Survival curve plots: {len(summary_data)}/{len(replicate_intersection)} patients")
print(f"  Fusion threshold (refit scale): {fusion_threshold:.6f}")
print(f"  Mean CI width (replicate): {replicate_stats['Uncertainty'].mean():.6f}")
print(f"\n  Refit fusion CoxPH C-index:")
print(f"    Discovery Harrell C: {harrell_disc:.4f}")
print(f"    Replicate Harrell C: {harrell_rep:.4f}")
print(f"\n  Open: {VISUALIZATION_DIR}/index.html")
print("=" * 80)