#!/usr/bin/env python3
"""DL-M2: Pairwise Late Fusion — Clinico-ResNet + Molecular (Cox PH)

Run from any directory:
    python 03_Late_Fusion_DLM2/Late_Fusion_Modeling_ResNet.py

Inputs (generated by the training notebooks):
    01_DLM1_Clinico_ResNet/outputs/data/discovery_results.csv
    01_DLM1_Clinico_ResNet/outputs/data/replicate_results.csv
    02_Molecular_Subtype/outputs/data/discovery_results.csv
    02_Molecular_Subtype/outputs/data/replicate_results.csv

NOTE: discovery_results.csv and replicate_results.csv contain per-patient risk
scores produced by the training notebooks (notebook 3) and are not included in
this repository. Run the training notebooks on your own CBTN data first.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import time
import pickle
import warnings
from datetime import datetime
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold
from sksurv.linear_model import CoxPHSurvivalAnalysis
from sksurv.metrics import concordance_index_censored, concordance_index_ipcw
from lifelines import KaplanMeierFitter
from lifelines.statistics import logrank_test
from scipy import stats

warnings.filterwarnings('ignore')
plt.style.use('default')
sns.set_palette("husl")

# ── Configuration ──────────────────────────────────────────────────────────────

# Repo root: two levels up from this script (03_Late_Fusion_DLM2/)
REPO_ROOT = Path(__file__).resolve().parent.parent

BASE_MODEL_PATHS = {
    'Clinical-ResNet': {
        'discovery': REPO_ROOT / '01_DLM1_Clinico_ResNet' / 'outputs' / 'data' / 'discovery_results.csv',
        'replicate': REPO_ROOT / '01_DLM1_Clinico_ResNet' / 'outputs' / 'data' / 'replicate_results.csv',
        'threshold': REPO_ROOT / '01_DLM1_Clinico_ResNet' / 'outputs' / 'metrics' / 'risk_thresholds.txt',
    },
    'Molecular': {
        'discovery': REPO_ROOT / '02_Molecular_Subtype' / 'outputs' / 'data' / 'discovery_results.csv',
        'replicate': REPO_ROOT / '02_Molecular_Subtype' / 'outputs' / 'data' / 'replicate_results.csv',
        'threshold': REPO_ROOT / '02_Molecular_Subtype' / 'outputs' / 'metrics' / 'risk_thresholds.txt',
    },
}

FUSION_NAME   = 'Clinico-ResNet + Molecular'
FEATURE_NAMES = ['Clinical-ResNet', 'Molecular']
MODEL_LABEL   = f'Pairwise ({FUSION_NAME})'

RISK_COLORS = {"High": "red", "Low": "blue"}

# ── Utilities ──────────────────────────────────────────────────────────────────

def timeit(start_time):
    elapsed = time.time() - start_time
    if elapsed < 60:   return f"{elapsed:.2f}s"
    if elapsed < 3600: return f"{elapsed/60:.2f}m"
    return f"{elapsed/3600:.2f}h"


def parse_threshold_file(filepath):
    try:
        with open(filepath, 'r') as f:
            for line in f:
                if '(50th percentile/median):' in line:
                    return float(line.split(':')[1].strip())
    except Exception as e:
        print(f"  ⚠️  Could not parse {filepath}: {e}")
    return None


def create_structured_outcomes(df):
    return np.array(
        [(bool(e), float(t)) for e, t in zip(df['Event'], df['Progression Free Survival'])],
        dtype=[("Event", bool), ("Progression Free Survival", float)]
    )


def max_event_time(y):
    """Return the largest observed event time in a structured survival array."""
    return float(y['Progression Free Survival'][y['Event']].max())


def compute_risk_group_ttest(risk_scores, threshold, cohort_label):
    groups     = np.where(risk_scores > threshold, 'High', 'Low')
    high_risks = risk_scores[groups == 'High']
    low_risks  = risk_scores[groups == 'Low']
    t_stat, p_val = stats.ttest_ind(high_risks, low_risks)
    return {
        'Cohort':      cohort_label,
        'N_High':      len(high_risks),
        'N_Low':       len(low_risks),
        'Mean_High':   float(np.mean(high_risks)),
        'Mean_Low':    float(np.mean(low_risks)),
        'T_Statistic': float(t_stat),
        'P_Value':     float(p_val),
        'Significant': p_val < 0.05,
    }

# ── Data Loading ───────────────────────────────────────────────────────────────

def load_models():
    print("=" * 70)
    print("PAIRWISE LATE FUSION: Clinico-ResNet + Molecular")
    print("=" * 70)
    print("\n[1/9] Loading model results...")

    models_data = {
        name: {
            'discovery': pd.read_csv(str(paths['discovery']), index_col='SubjectID'),
            'replicate': pd.read_csv(str(paths['replicate']), index_col='SubjectID'),
        }
        for name, paths in BASE_MODEL_PATHS.items()
    }

    for name, data in models_data.items():
        print(f"  {name:<20}  Discovery: {len(data['discovery']):>3}  "
              f"Replicate: {len(data['replicate']):>3}")

    return models_data


def load_thresholds():
    print("\n[2/9] Loading model thresholds...")
    thresholds = {}
    for name, paths in BASE_MODEL_PATHS.items():
        t = parse_threshold_file(str(paths['threshold']))
        if t is not None:
            thresholds[name] = t
            print(f"  ✓ {name:<20}  Threshold: {t:.6f}")
        else:
            print(f"  ⚠️  {name:<20}  Will use median")
    return thresholds

# ── Intersection + Standardization ────────────────────────────────────────────

def build_intersection(models_data):
    print("\n[3/9] Finding pairwise patient intersection...")

    disc_ids = set.intersection(*[set(models_data[m]['discovery'].index) for m in FEATURE_NAMES])
    rep_ids  = set.intersection(*[set(models_data[m]['replicate'].index)  for m in FEATURE_NAMES])

    disc_ids = sorted(disc_ids)
    rep_ids  = sorted(rep_ids)

    print(f"  Discovery: {len(disc_ids)} patients")
    print(f"  Replicate: {len(rep_ids)} patients")

    return disc_ids, rep_ids


def extract_and_scale(models_data, disc_ids, rep_ids):
    print("\n[4/9] Extracting and standardising risk scores...")

    raw    = {'discovery': {}, 'replicate': {}}
    scaled = {'discovery': {}, 'replicate': {}}
    scalers = {}

    for model in FEATURE_NAMES:
        raw['discovery'][model] = models_data[model]['discovery'].loc[disc_ids, 'Risk Score'].values
        raw['replicate'][model] = models_data[model]['replicate'].loc[rep_ids,  'Risk Score'].values

        scaler = StandardScaler().fit(raw['discovery'][model].reshape(-1, 1))
        scalers[model] = scaler

        scaled['discovery'][model] = scaler.transform(raw['discovery'][model].reshape(-1, 1)).flatten()
        scaled['replicate'][model] = scaler.transform(raw['replicate'][model].reshape(-1, 1)).flatten()

    outcomes = {
        'discovery': create_structured_outcomes(models_data[FEATURE_NAMES[0]]['discovery'].loc[disc_ids]),
        'replicate': create_structured_outcomes(models_data[FEATURE_NAMES[0]]['replicate'].loc[rep_ids]),
    }

    print("  ✓ Done")
    return raw, scaled, scalers, outcomes

# ── Cross-Validation ───────────────────────────────────────────────────────────

def run_cv(X, y):
    print("\n[5/9] Running 10-fold stratified CV...")
    start = time.time()
    cv    = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
    rows  = []

    for fold, (tr, te) in enumerate(cv.split(X, y["Event"]), 1):
        try:
            est = CoxPHSurvivalAnalysis(alpha=0.0, verbose=0)
            est.fit(X[tr], y[tr])
            pred = est.predict(X[te])

            har = concordance_index_censored(y[te]["Event"], y[te]["Progression Free Survival"], pred)[0]

            try:
                tau = max_event_time(y[tr])
                uno = concordance_index_ipcw(y[tr], y[te], pred, tau=tau)[0]
            except Exception:
                uno = np.nan

            rows.append({
                'fold': fold, 'harrell': har, 'uno': uno,
                'coef_Clinical-ResNet': est.coef_[0],
                'coef_Molecular':       est.coef_[1],
            })
        except Exception as e:
            print(f"  Fold {fold} error: {e}")

    cv_df = pd.DataFrame(rows)
    print(f"  ✓ Complete ({timeit(start)})  "
          f"Mean Harrell C: {cv_df['harrell'].mean():.4f} ± {cv_df['harrell'].std():.4f}")
    return cv_df


def cv_summary(cv_df):
    n = len(cv_df)
    summary = {}
    for metric in ['harrell', 'uno']:
        mu  = cv_df[metric].mean()
        std = cv_df[metric].std()
        se  = std / np.sqrt(n)
        summary[metric] = {
            'mean': mu, 'std': std, 'se': se,
            'ci_lower': mu - 1.96 * se,
            'ci_upper': mu + 1.96 * se,
            'min': cv_df[metric].min(),
            'max': cv_df[metric].max(),
        }
    return summary

# ── Train Final Model ──────────────────────────────────────────────────────────

def train_final(X_disc, X_rep, outcomes):
    print("\n[6/9] Training final model on full discovery set...")

    est = CoxPHSurvivalAnalysis(alpha=0.0, verbose=0)
    est.fit(X_disc, outcomes['discovery'])

    preds = {
        'discovery': est.predict(X_disc),
        'replicate': est.predict(X_rep),
    }

    coef_abs = np.abs(est.coef_)
    weights  = {FEATURE_NAMES[i]: float(coef_abs[i] / coef_abs.sum()) for i in range(2)}

    print(f"  Coefficients  →  {FEATURE_NAMES[0]}: {est.coef_[0]:.4f}  |  "
          f"{FEATURE_NAMES[1]}: {est.coef_[1]:.4f}")
    print(f"  Norm weights  →  {FEATURE_NAMES[0]}: {weights[FEATURE_NAMES[0]]:.3f}  |  "
          f"{FEATURE_NAMES[1]}: {weights[FEATURE_NAMES[1]]:.3f}")

    return est, preds, weights

# ── Survival Functions ─────────────────────────────────────────────────────────

def predict_survival(estimator, X_disc, X_rep, disc_ids, rep_ids, out_dir):
    print("\n[7/9] Predicting survival functions (0–60 months)...")

    time_points = np.arange(0, 61, 1)
    key_times   = [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60]

    surv = {}
    for label, X, ids in [('discovery', X_disc, disc_ids), ('replicate', X_rep, rep_ids)]:
        fns   = estimator.predict_survival_function(X)
        probs = np.array([[fn(t) for t in time_points] for fn in fns])
        surv[label] = {'time_points': time_points, 'survival_probabilities': probs, 'patient_ids': ids}

        print(f"  {label.capitalize():>10}: {probs.shape[0]} patients  |  "
              f"1-yr {probs[:, 12].mean():.1%}  3-yr {probs[:, 36].mean():.1%}  "
              f"5-yr {probs[:, 60].mean():.1%}")

        df = pd.DataFrame(
            probs[:, key_times],
            index=ids,
            columns=[f"{t}mo" for t in key_times]
        )
        df.index.name = 'SubjectID'
        df.to_csv(os.path.join(out_dir, f'survival_predictions_{label}.csv'))

    with open(os.path.join(out_dir, 'survival_predictions.pkl'), 'wb') as f:
        pickle.dump(surv, f)

    print("  ✓ Saved CSVs + pickle")
    return surv

# ── Kaplan-Meier ───────────────────────────────────────────────────────────────

def plot_km(risk_scores, outcomes_struct, cohort_label, plots_dir, threshold):
    df = pd.DataFrame({
        'Risk Score':                risk_scores,
        'Progression Free Survival': outcomes_struct['Progression Free Survival'],
        'Event':                     outcomes_struct['Event'],
    })
    df['Risk Group'] = np.where(df['Risk Score'] > threshold, 'High', 'Low')

    high_df = df[df['Risk Group'] == 'High']
    low_df  = df[df['Risk Group'] == 'Low']

    lr    = logrank_test(
        high_df['Progression Free Survival'], low_df['Progression Free Survival'],
        event_observed_A=high_df['Event'], event_observed_B=low_df['Event'],
    )
    p_val = lr.p_value
    p_str = 'p < 0.001' if p_val < 0.001 else f'p = {p_val:.3f}'

    max_t      = df['Progression Free Survival'].max()
    col_labels = list(range(0, int(max_t) + 1, 20))
    kmf        = KaplanMeierFitter()

    fig, ax1 = plt.subplots(figsize=(10, 6))
    ax2 = fig.add_subplot(212, frameon=False)

    cell_texts = []
    row_labels = []

    for group in ['High', 'Low']:
        gdf = df[df['Risk Group'] == group]
        if len(gdf) == 0:
            continue

        kmf.fit(
            gdf['Progression Free Survival'],
            event_observed=gdf['Event'].astype(int),
            label=group,
        )
        kmf.plot(ax=ax1, color=RISK_COLORS[group], ci_show=False, legend=True)

        censored = gdf[gdf['Event'] == False]
        if len(censored) > 0:
            ax1.plot(
                censored['Progression Free Survival'],
                kmf.survival_function_at_times(censored['Progression Free Survival']).values,
                '+', color=RISK_COLORS[group], markersize=6,
            )

        kmf.event_table['event_interval'] = (kmf.event_table.index // 20 * 20).astype(int)
        risk_at = kmf.event_table.groupby('event_interval')['at_risk'].max().to_dict()
        cell_texts.append([str(risk_at.get(t, 0)) for t in col_labels])
        row_labels.append(group)

    # ── p-value annotation (upper-right, matching first script) ──
    ax1.annotate(
        f'Log-rank {p_str}',
        xy=(0.97, 0.97),
        xycoords='axes fraction',
        ha='right', va='top',
        fontsize=11,
        bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='black', alpha=0.8),
    )

    ax1.set_xlabel('Time (Months)', fontsize=12)
    ax1.set_ylabel('Progression-free survival probability', fontsize=12)
    ax1.set_title(f'Clinico-ResNet + Molecular — {cohort_label} Cohort', fontweight='bold', fontsize=14)
    ax1.grid(True, alpha=0.3)

    legend = ax1.legend(title='Risk Group', loc='lower left', frameon=True)
    legend.get_frame().set_facecolor('white')
    legend.get_frame().set_edgecolor('black')

    ax2.axis('off')
    table = ax2.table(
        cellText=cell_texts,
        cellLoc='center',
        rowLabels=row_labels,
        rowColours=[RISK_COLORS[g] for g in row_labels],
        colLabels=col_labels,
        loc='bottom',
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9)

    path = os.path.join(plots_dir, f'KM_Clinico-ResNet_Molecular_{cohort_label}.png')
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"  ✓ {os.path.basename(path)}  |  Log-rank {p_str}")

    return {
        'Cohort':      cohort_label,
        'N_High':      len(high_df),
        'N_Low':       len(low_df),
        'LogRank_P':   float(p_val),
        'Significant': p_val < 0.05,
    }
# ── Evaluation ─────────────────────────────────────────────────────────────────

def evaluate(preds, outcomes, models_data, disc_ids, rep_ids):
    print("\n[8/9] Evaluating models...")
    rows = []

    disc_out = create_structured_outcomes(models_data[FEATURE_NAMES[0]]['discovery'].loc[disc_ids])
    rep_out  = create_structured_outcomes(models_data[FEATURE_NAMES[0]]['replicate'].loc[rep_ids])
    tau_disc = max_event_time(disc_out)

    # Base models
    for model in FEATURE_NAMES:
        for cohort, ids, out, train_out, tau in [
            ('Discovery', disc_ids, disc_out, disc_out, max_event_time(disc_out)),
            ('Replicate',  rep_ids,  rep_out,  disc_out, tau_disc),
        ]:
            risk = models_data[model][cohort.lower()].loc[ids, 'Risk Score'].values
            har  = concordance_index_censored(out['Event'], out['Progression Free Survival'], risk)[0]
            try:
                uno = concordance_index_ipcw(train_out, out, risk, tau=tau)[0]
            except Exception as e:
                print(f"    Uno C failed ({model}, {cohort}): {e}")
                uno = np.nan

            rows.append({'Model': model, 'Cohort': cohort,
                         'N': len(ids), 'Harrell_C': round(har, 4),
                         'Uno_C': round(uno, 4) if not np.isnan(uno) else np.nan})

    # Fusion model
    for cohort, risk, out, train_out, tau in [
        ('Discovery', preds['discovery'], outcomes['discovery'], outcomes['discovery'], max_event_time(outcomes['discovery'])),
        ('Replicate',  preds['replicate'],  outcomes['replicate'],  outcomes['discovery'], tau_disc),
    ]:
        har = concordance_index_censored(out['Event'], out['Progression Free Survival'], risk)[0]
        try:
            uno = concordance_index_ipcw(train_out, out, risk, tau=tau)[0]
        except Exception as e:
            print(f"    Uno C failed ({MODEL_LABEL}, {cohort}): {e}")
            uno = np.nan

        rows.append({'Model': MODEL_LABEL, 'Cohort': cohort,
                     'N': len(disc_ids) if cohort == 'Discovery' else len(rep_ids),
                     'Harrell_C': round(har, 4),
                     'Uno_C': round(uno, 4) if not np.isnan(uno) else np.nan})

    df = pd.DataFrame(rows)
    print(df.to_string(index=False))
    return df

# ── Save Everything ────────────────────────────────────────────────────────────

def save_results(out_dir, estimator, scalers, cv_df, cv_sum, eval_df,
                 preds, outcomes, weights, disc_ids, rep_ids,
                 threshold, logrank_rows):
    print("\n[9/9] Saving results...")

    eval_df.to_csv(os.path.join(out_dir, 'performance_summary.csv'), index=False)
    cv_df.to_csv(os.path.join(out_dir, 'cv_results_folds.csv'), index=False)

    ci_rows = []
    for metric, s in cv_sum.items():
        ci_rows.append({
            'Metric': metric,
            'Mean': s['mean'], 'Std': s['std'], 'SE': s['se'],
            'CI_Lower_95': s['ci_lower'], 'CI_Upper_95': s['ci_upper'],
            'Min': s['min'], 'Max': s['max'],
        })
    pd.DataFrame(ci_rows).to_csv(os.path.join(out_dir, 'cv_summary_ci.csv'), index=False)

    pd.DataFrame([weights]).to_csv(os.path.join(out_dir, 'fusion_weights.csv'), index=False)

    for cohort, risk, ids, out in [
        ('discovery', preds['discovery'], disc_ids, outcomes['discovery']),
        ('replicate',  preds['replicate'],  rep_ids,  outcomes['replicate']),
    ]:
        pd.DataFrame({
            'SubjectID': ids,
            'Risk Score': risk,
            'Risk Group': ['High' if r > threshold else 'Low' for r in risk],
            'Progression Free Survival': out['Progression Free Survival'],
            'Event': out['Event'],
        }).to_csv(os.path.join(out_dir, f'risk_scores_{cohort}.csv'), index=False)

    with open(os.path.join(out_dir, 'threshold.txt'), 'w') as f:
        f.write(f"Fusion threshold (median of discovery risk scores): {threshold:.6f}\n")
        f.write(f"Discovery N: {len(disc_ids)}\nReplicate N: {len(rep_ids)}\n")

    # ── Risk group t-test ──────────────────────────────────────────────────────
    ttest_rows = []
    for cohort, risk in [
        ('Discovery', preds['discovery']),
        ('Replicate',  preds['replicate']),
    ]:
        result = compute_risk_group_ttest(risk, threshold, cohort)
        ttest_rows.append(result)
        print(f"  {cohort} t-test: t={result['T_Statistic']:.4f}, "
              f"p={result['P_Value']:.4e}, "
              f"High (n={result['N_High']}) vs Low (n={result['N_Low']})")

    pd.DataFrame(ttest_rows).to_csv(
        os.path.join(out_dir, 'risk_group_ttest.csv'), index=False)
    print("  ✓ Saved: risk_group_ttest.csv")

    # ── Log-rank results ───────────────────────────────────────────────────────
    pd.DataFrame(logrank_rows).to_csv(
        os.path.join(out_dir, 'risk_group_logrank.csv'), index=False)
    print("  ✓ Saved: risk_group_logrank.csv")

    with open(os.path.join(out_dir, 'model.pkl'), 'wb') as f:
        pickle.dump(estimator, f)
    with open(os.path.join(out_dir, 'scalers.pkl'), 'wb') as f:
        pickle.dump(scalers, f)

    print("\n" + "=" * 60)
    print("CROSS-VALIDATION SUMMARY (10-fold)")
    print("=" * 60)
    for metric, s in cv_sum.items():
        label = "Harrell's C" if metric == 'harrell' else "Uno's C"
        print(f"\n  {label}:")
        print(f"    Mean ± SD : {s['mean']:.4f} ± {s['std']:.4f}")
        print(f"    95% CI    : [{s['ci_lower']:.4f}, {s['ci_upper']:.4f}]")
        print(f"    Range     : [{s['min']:.4f}, {s['max']:.4f}]")
    print("=" * 60)

    print(f"\n✓ All outputs saved to: {out_dir}")

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_dir   = str(REPO_ROOT / f"03_Late_Fusion_DLM2/outputs/pairwise_resnet_molecular_{timestamp}")
    plots_dir = os.path.join(out_dir, 'plots')
    os.makedirs(plots_dir, exist_ok=True)
    print(f"\nOutput directory: {out_dir}")

    models_data = load_models()
    _thresholds = load_thresholds()

    disc_ids, rep_ids = build_intersection(models_data)
    raw, scaled, scalers, outcomes = extract_and_scale(models_data, disc_ids, rep_ids)

    X_disc = np.column_stack([scaled['discovery'][m] for m in FEATURE_NAMES])
    X_rep  = np.column_stack([scaled['replicate'][m]  for m in FEATURE_NAMES])

    cv_df  = run_cv(X_disc, outcomes['discovery'])
    cv_sum = cv_summary(cv_df)

    estimator, preds, weights = train_final(X_disc, X_rep, outcomes)

    threshold = float(np.median(preds['discovery']))

    print("\n[7/9] Predicting survival & plotting KM curves...")
    surv_preds = predict_survival(estimator, X_disc, X_rep, disc_ids, rep_ids, out_dir)

    logrank_rows = []
    for cohort, risk, out in [
        ('Discovery', preds['discovery'], outcomes['discovery']),
        ('Replicate',  preds['replicate'],  outcomes['replicate']),
    ]:
        lr_result = plot_km(risk, out, cohort, plots_dir, threshold=threshold)
        logrank_rows.append(lr_result)

    eval_df = evaluate(preds, outcomes, models_data, disc_ids, rep_ids)

    save_results(out_dir, estimator, scalers, cv_df, cv_sum, eval_df,
                 preds, outcomes, weights, disc_ids, rep_ids,
                 threshold, logrank_rows)

    print("\n" + "=" * 70)
    print("DONE")
    print("=" * 70)
    print(f"\nKey outputs:")
    print(f"  performance_summary.csv   — base + fusion C-indices")
    print(f"  cv_summary_ci.csv         — 10-fold CV with 95% CI")
    print(f"  risk_scores_*.csv         — per-patient risk scores + groups")
    print(f"  survival_predictions_*.csv— survival probabilities (0–60 mo)")
    print(f"  risk_group_ttest.csv      — t-test: High vs Low risk scores")
    print(f"  risk_group_logrank.csv    — log-rank: KM curve separation")
    print(f"  plots/                    — KM curves with log-rank p-value")
    print("=" * 70)

    return out_dir, eval_df


if __name__ == "__main__":
    main()